### PR TITLE
staticanalysis/frontend: Detect killed tasks, fixes #1927

### LINKED ISSUE #1927: Get failed status when tasks get killed by Taskcluster
We show an invalid status `started` when tasks fail during the clone and get killed by Taskcluster.
The taskcluster index is not updated, so it stays in its initial place.

I think it's almost impossible to fix in the task code, but we could update the index from pulselistener in that case.

Suggestions welcome.

### PR DESCRIPTION
**Pull request by La0**
This gives me the following stats:

### CODE REVIEW

File: src/staticanalysis/frontend/src/Choice.vue [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default {
   },
   mounted: function () {
     let initial = this.$route.query[this.name]
-    if (initial) {
+    if (initial && this.choices) {
```
Comment (La0) [inline src/staticanalysis/frontend/src/Choice.vue]: Unrelated bug i noticed in devtools

File: src/staticanalysis/frontend/src/store.js [hunk 2]
```diff
@@ -8,6 +8,8 @@ const PREFERENCES_KEY = 'mozilla-sa-dashboard'
 const TASKCLUSTER_INDEX = 'https://index.taskcluster.net/v1'
 const TASKCLUSTER_QUEUE = 'https://queue.taskcluster.net/v1'
 const TASKS_SLICE = 10
+const FINAL_STATES = ['done', 'error']
+const MAX_TTL = 2 * 3600 * 1000 // 2 hours in ms
```
Comment (marco-c) [inline src/staticanalysis/frontend/src/store.js]: Can you add a comment here and where we set the deadline for the task so that we remember to keep them in sync?

File: src/staticanalysis/frontend/src/Tasks.vue [hunk 3]
```diff
@@ -126,6 +126,9 @@ export default {
             <span class="tag is-info" v-else-if="task.data.state == 'cloned'">Cloned</span>
             <span class="tag is-info" v-else-if="task.data.state == 'analyzing'">Analyzing</span>
             <span class="tag is-primary" v-else-if="task.data.state == 'analyzed'">Analyzed</span>
+            <span class="tag is-danger" v-else-if="task.data.state == 'killed'">
+              Killed
```
Comment (marco-c) [inline src/staticanalysis/frontend/src/Tasks.vue]: Nit: maybe something more descriptive, like "Killed for timeout" or "Killed because exceeded deadline"
