### PR TITLE
Fixes #2226. Disables "Do eet" button and shows "Working..." when release promoted

### LINKED ISSUE #2226: [shipit] Don't allow promoting the same release twice
The Firefox `69.0b9` beta release was accidentally promoted twice. Ship It was then in an invalid state, since it was only tracking the second promotion, but the first promotion still existed and was hogging resources. Cancelling the release only cancelled the second graph.

**To reproduce:**
1. Click to promote a release
2. Click "do eet" multiple times
3. Multiple graphs are created

**Expected behaviour:**
* [ ] The server that's receiving the requests shouldn't allow more than one promotion for a release
* [ ] The web frontend should disable the "do eet" button while the request to the server is in-progress

### PR DESCRIPTION
**Pull request by mitchhentges**

### CODE REVIEW

File: src/shipit/frontend/src/views/ListReleases/index.js [hunk 1]
```diff
@@ -530,7 +543,7 @@ class TaskLabel extends React.PureComponent {
                   <Button
                     onClick={this.doEet}
                     bsStyle="danger"
-                    disabled={!this.context.authController.userSession && !this.state.submitted}
+                    disabled={!this.context.authController.userSession || this.state.inProgress}
```
Comment (mitchhentges) [inline src/shipit/frontend/src/views/ListReleases/index.js]: I matched the logic in `NewRelease/index.js` which does `|| this.state.inProgress` instead of `&& !this.state.submitted`
